services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redisDB:/data
    networks:
      - gin-redis
    expose:
      - 6379

  backend:
    build:
      context: backend
      target: builder
    ports:
      - 8080:8080
    networks:
      - gin-nginx
      - gin-redis
    depends_on: 
      - redis

  proxy:
    build: proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - backend
    networks:
      - gin-nginx

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  gin-nginx: {}
  gin-redis: {}
volumes:
  redisDB: